Repository LeelaChessZero/lc0, pull requests merged in 2018-08, with the labels that each got.

#146 Network_check: support backends choice and add many options.
  meson.build
  src/neural/network_check.cc
  src/utils/histogram.cc
  src/utils/histogram.h
Labels: enhancement, lc0

#260 Cache history length is int. Turned out it has always been 1.
  src/mcts/search.h
Labels: bug

#131 Complete: use Tilps' Syzygy port to integrate WDL probing into search
  meson.build
  src/chess/bitboard.h
  src/chess/board.cc
  src/chess/board.h
  src/chess/callbacks.h
  src/chess/position.cc
  src/chess/position.h
  src/chess/uciloop.cc
  src/engine.cc
  src/engine.h
  src/mcts/node.cc
  src/mcts/node.h
  src/mcts/search.cc
  src/mcts/search.h
  src/neural/encoder.cc
  src/selfplay/game.cc
  src/syzygy/syzygy.cc
  src/syzygy/syzygy.h
  src/syzygy/syzygy_test.cc
Labels: enhancement
