Repository LeelaChessZero/lc0, pull requests merged in 2022-11, with the labels that each got.

#1752 cudnn attention policy
  src/neural/cuda/network_cudnn.cc
Labels: rfc

#1781 Add encoder support to blas/eigen backend.
  src/neural/blas/encoder.h
  src/neural/blas/network_blas.cc
Labels: rfc, testing required

#1647 Chessbase adds a UTF-8 BOM to the PGN files, so ignore those if they appear
  src/chess/pgn.h
Labels: rfc

#1783 Add attention policy and mish support to onnx backend.
  src/neural/onnx/adapters.h
  src/neural/onnx/builder.cc
  src/neural/onnx/builder.h
  src/neural/onnx/converter.cc
  src/neural/onnx/network_onnx.cc
Labels: testing required
