Repository LeelaChessZero/lc0, pull requests merged in 2022-12, with the labels that each got.

#1764 Add 'simple' time manager
  meson.build
  src/mcts/stoppers/factory.cc
  src/mcts/stoppers/simple.cc
  src/mcts/stoppers/simple.h
Labels: rfc, testing required

#1546 Backendbench assistant with TC-dependent output.
  src/benchmark/backendbench.cc
Labels: rfc, testing required

#1762 In smooth TM, use piggybank when it seems like the bestmove can be overtaken.
  src/mcts/stoppers/smooth.cc
  src/mcts/stoppers/stoppers.cc
Labels: bug fix

#1742 Fix apparent "mate blindness" in endgame due to instamove logic
  src/mcts/search.cc
  src/mcts/stoppers/stoppers.cc
  src/mcts/stoppers/timemgr.h
Labels: rfc, bug fix, testing required

#1684 initial dfrc support
  src/chess/board.cc
  src/chess/board.h
  src/chess/pgn.h
  src/neural/decoder.cc
  src/neural/encoder.cc
  src/trainingdata/trainingdata.cc
Labels: testing required

#1681 add probability for early termination of selfplay openings
  src/selfplay/game.cc
  src/selfplay/game.h
  src/selfplay/tournament.cc
Labels: rfc, testing required
